# Site settings
title:          Tail
description:    "Minimal Jekyll blog theme"
baseurl:        "/tail"
url:

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Kolkata

# Google Analytics
google_analytics:

# Author
#   This is the default author name displayed on all posts, can be overridden by setting a different `author: Your Name`
#   in the frontmatter
author:
  name:         Your Name

# Build settings
markdown:       kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
include:
  - _pages

# Assets
sass:
  sass_dir:     /assets/css/_sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude:
  - README.md
  - LICENSE.md

# Disqus (Set to your disqus id)
disqus:
